In [97]:
# Importaçao das bibliotecas
import pandas as pd
from sklearn.neighbors import KNeighborsClassifier # KNeighborsClassifier utiliza dist euclidiana
from sklearn.metrics import accuracy_score

In [106]:
# Encontrando o y previsto para a instância N4

# Carregamento dos dados

# Dados Normalizados 2 Features
df_norm_2features_testing = pd.read_csv('Dados_Normalizados_2Features/TestingData_2F_Norm.txt', sep='\t')
df_norm_2features_training = pd.read_csv('Dados_Normalizados_2Features/TrainingData_2F_Norm.txt', sep='\t')

# Dados Normalizados 11 Features
df_norm_11features_testing = pd.read_csv('Dados_Normalizados_11Features/TestingData_11F_Norm.txt', sep='\t')
df_norm_11features_training = pd.read_csv('Dados_Normalizados_11Features/TrainingData_11F_Norm.txt', sep='\t')

# Seleção de Features
features_2features = ['total.sulfur.dioxide', 'citric.acid']
features_11features = ['fixed.acidity', 'volatile.acidity', 'citric.acid', 'residual.sugar', 'chlorides', 'free.sulfur.dioxide', 'total.sulfur.dioxide', 'density', 'pH', 'sulphates', 'alcohol']

label = ['class']

# Preparacao dos dados de treino
# Dados Normalizados 2 Features
x_train_2features_norm = df_norm_2features_training.loc[:, features_2features]
y_train_2features_norm = df_norm_2features_training.loc[:, label].values.ravel()

# Dados Normalizados 11 Features
x_train_11features_norm = df_norm_11features_training.loc[:, features_11features]
y_train_11features_norm = df_norm_11features_training.loc[:, label].values.ravel()

# Preparacao dos dados de teste
# Dados Normalizados 2 Features
x_test_2features_norm = df_norm_2features_testing.loc[:, features_2features]
y_test_2features_norm = df_norm_2features_testing.loc[:, label].values.ravel()

# Dados Normalizados 11 Features
x_test_11features_norm = df_norm_11features_testing.loc[:, features_11features]
y_test_11features_norm = df_norm_11features_testing.loc[:, label].values.ravel()

# Modelo KNN com k = 5
# Dados Normalizados 2 Features
knn_classifier_norm_2features = KNeighborsClassifier( n_neighbors= 5 )

# Dados Normalizados 11 Features
knn_classifier_norm_11features = KNeighborsClassifier( n_neighbors= 5 )

# Encaixando o modelo ao Training Dataset
# Dados Normalizados 2 Features
knn_classifier_norm_2features.fit( x_train_2features_norm, y_train_2features_norm )

# Dados Normalizados 11 Features
knn_classifier_norm_11features.fit( x_train_11features_norm, y_train_11features_norm )

# Prevendo label para Testing Dataset
# Dados Normalizados 2 Features
y_pred_norm_2features = knn_classifier_norm_2features.predict( x_test_2features_norm )

# Dados Normalizados 11 Features
y_pred_norm_11features = knn_classifier_norm_11features.predict( x_test_11features_norm )

# Comparando y de teste e y previsto
# Dados Normalizados 2 Features
df_norm_2features_testing_N4 = df_norm_2features_testing
df_norm_2features_testing_N4['previsto'] = y_pred_norm_2features
print(f'Resultado obtido para 2 features normalizadas:\n{df_norm_2features_testing_N4}')

# Dados Normalizados 11 Features
df_norm_11features_testing_N4 = df_norm_11features_testing
df_norm_11features_testing_N4['previsto'] = y_pred_norm_11features
print(f'\nResultado obtido para 11 features normalizadas:\n{df_norm_11features_testing_N4[["ID", "citric.acid", "class","previsto"]]}')

Resultado obtido para 2 features normalizadas:
   ID  total.sulfur.dioxide  citric.acid  class  previsto
0  N1                 0.134        0.000      0         0
1  N2                 0.496        0.441      0         1
2  N3                 0.031        0.735      1         1
3  N4                 0.181        1.000      1         1

Resultado obtido para 11 features normalizadas:
   ID  citric.acid  class  previsto
0  N1        0.000      0         0
1  N2        0.441      0         0
2  N3        0.735      1         1
3  N4        1.000      1         0

In [112]:
# Buscando os 5 vizinhos mais próximos a N4
ponto_teste_N4_2features = x_test_2features_norm.iloc[[3]]
ponto_teste_N4_11features = x_test_11features_norm.iloc[[3]]

# Encontrando instâncias mais próximas ao ponto desejado
distancia_N4_2features, indice_N4_2features = knn_classifier_norm_2features.kneighbors(ponto_teste_N4_2features , n_neighbors = 5)
distancia_N4_11features, indice_N4_11features = knn_classifier_norm_11features.kneighbors(ponto_teste_N4_11features , n_neighbors = 5)

print('Para Dados Normalizados 2 Features:')
print(f'Os índices dos 5 vizinhos mais próximos a N4: {indice_N4_2features}')
print(f'Distâncias dos vizinhos em relação a N4: {distancia_N4_2features}')

print('\nPara Dados Normalizados 11 Features:')
print(f'Os índices dos 5 vizinhos mais próximos a N4: {indice_N4_11features}')
print(f'Distâncias dos vizinhos em relação a N4: {distancia_N4_11features}')

Para Dados Normalizados 2 Features:
Os índices dos 5 vizinhos mais próximos a N4: [[31  6  7 37 29]]
Distâncias dos vizinhos em relação a N4: [[0.087      0.14200352 0.16131956 0.25770138 0.28436948]]

Para Dados Normalizados 11 Features:
Os índices dos 5 vizinhos mais próximos a N4: [[29  0  7  6  5]]
Distâncias dos vizinhos em relação a N4: [[1.92418424 2.04533371 2.04690547 2.46220227 2.49820516]]

In [113]:
df_norm_2features_training

     ID  total.sulfur.dioxide  citric.acid  class
0    T1                 0.638        0.559      0
1    T2                 0.795        0.441      0
2    T3                 0.409        0.603      0
3    T4                 0.539        0.000      0
4    T5                 0.236        0.515      0
5    T6                 0.071        0.559      0
6    T7                 0.102        0.882      0
7    T8                 0.071        0.882      0
8    T9                 0.173        0.382      0
9   T10                 0.488        0.956      0
10  T11                 0.165        0.029      0
11  T12                 0.402        0.324      0
12  T13                 0.748        0.471      0
13  T14                 0.268        0.721      0
14  T15                 0.016        0.029      0
15  T16                 0.197        0.118      0
16  T17                 0.654        0.294      0
17  T18                 0.000        0.059      0
18  T19                 0.244        0.221      0
19  T20                 0.220        0.206      0
20  T21                 0.134        0.588      0
21  T22                 0.339        0.515      0
22  T23                 0.307        0.574      1
23  T24                 0.425        0.000      1
24  T25                 0.150        0.353      1
25  T26                 0.197        0.691      1
26  T27                 0.126        0.015      1
27  T28                 0.024        0.706      1
28  T29                 0.031        0.721      1
29  T30                 0.126        0.721      1
30  T31                 0.425        0.368      1
31  T32                 0.268        1.000      1
32  T33                 0.260        0.074      1
33  T34                 0.331        0.471      1
34  T35                 0.063        0.618      1
35  T36                 0.543        0.721      1
36  T37                 0.480        0.338      1
37  T38                 0.354        0.809      1
38  T39                 0.071        0.338      1
39  T40                 0.094        0.103      1
40  T41                 0.055        0.662      1
41  T42                 0.409        0.088      1
42  T43                 1.000        0.412      1
43  T44                 0.244        0.721      1

In [114]:
df_norm_11features_training

,ID,fixed.acidity,volatile.acidity,citric.acid,residual.sugar,chlorides,free.sulfur.dioxide,total.sulfur.dioxide,density,pH,sulphates,alcohol,class
0,T1,0.449,0.278,0.559,0.015,0.985,0.489,0.638,0.769,0.293,0.150,0.000,0
1,T2,0.168,0.685,0.441,0.455,0.220,0.340,0.795,0.769,0.493,0.490,0.266,0
2,T3,0.439,0.222,0.603,0.121,0.333,0.149,0.409,0.673,0.373,0.052,0.156,0
3,T4,0.131,0.741,0.000,0.424,0.409,1.000,0.539,0.406,0.360,0.020,0.156,0
4,T5,0.168,0.352,0.515,0.015,0.371,0.255,0.236,0.459,0.547,0.085,0.109,0
5,T6,0.318,0.537,0.559,0.000,0.432,0.021,0.071,0.516,0.360,0.065,0.141,0
6,T7,0.280,0.093,0.882,0.227,0.492,0.128,0.102,0.682,0.613,0.170,0.328,0
7,T8,0.505,0.241,0.882,0.106,0.856,0.064,0.071,0.714,0.147,0.418,0.141,0
8,T9,0.234,0.481,0.382,0.061,0.174,0.106,0.173,0.510,0.613,0.144,0.172,0
9,T10,1.000,0.241,0.956,0.909,0.432,0.383,0.488,0.612,0.067,0.275,1.000,0
10,T11,0.159,0.741,0.029,0.061,0.295,0.298,0.165,0.563,0.627,0.216,0.203,0
11,T12,0.215,0.667,0.324,0.045,0.326,0.830,0.402,0.346,0.227,0.000,0.109,0
12,T13,0.196,0.852,0.471,0.106,0.227,0.660,0.748,0.482,0.533,0.059,0.156,0
13,T14,0.673,0.352,0.721,0.470,0.258,0.319,0.268,0.633,0.120,0.124,0.156,0
14,T15,0.112,0.630,0.029,0.045,0.212,0.000,0.016,0.551,0.707,0.170,0.156,0
15,T16,0.140,0.463,0.118,0.091,0.189,0.298,0.197,0.400,0.533,0.144,0.187,0
16,T17,0.215,1.000,0.294,1.000,0.447,0.553,0.654,0.747,0.360,0.105,0.109,0
17,T18,0.234,0.796,0.059,0.015,0.000,0.000,0.000,0.469,0.627,0.033,0.141,0
18,T19,0.159,0.593,0.221,0.106,0.280,0.319,0.244,0.459,0.640,0.111,0.250,0
19,T20,0.178,0.426,0.206,0.197,0.280,0.234,0.220,0.473,0.573,0.046,0.344,0
20,T21,0.449,0.111,0.588,0.212,0.447,0.128,0.134,0.918,0.733,0.320,0.187,0
21,T22,0.262,0.722,0.515,0.197,0.356,0.511,0.339,0.551,0.507,0.131,0.359,0
22,T23,0.280,0.185,0.574,0.152,0.265,0.532,0.307,0.376,0.520,0.301,0.609,1
23,T24,0.000,0.204,0.000,0.045,0.083,0.489,0.425,0.000,1.000,0.242,0.859,1
24,T25,0.215,0.593,0.353,0.076,0.295,0.128,0.150,0.684,0.693,0.235,0.156,1
25,T26,0.551,0.352,0.691,0.174,0.348,0.106,0.197,0.588,0.413,0.229,0.562,1
26,T27,0.150,0.519,0.015,0.091,0.265,0.106,0.126,0.429,0.533,0.092,0.156,1
27,T28,0.290,0.093,0.706,0.091,0.409,0.043,0.024,0.253,0.440,0.131,0.609,1
28,T29,0.467,0.111,0.721,0.167,0.152,0.021,0.031,0.612,0.160,0.209,0.312,1
29,T30,0.355,0.556,0.721,0.061,1.000,0.043,0.126,0.602,0.453,0.124,0.141,1
30,T31,0.234,0.370,0.368,0.167,0.258,0.532,0.425,0.464,0.587,0.105,0.312,1
31,T32,0.794,0.343,1.000,0.212,0.348,0.277,0.268,1.000,0.173,0.248,0.234,1
32,T33,0.206,0.722,0.074,0.061,0.220,0.426,0.260,0.459,0.653,0.098,0.469,1
33,T34,0.308,0.259,0.471,0.045,0.205,0.468,0.331,0.302,0.600,0.196,0.516,1
34,T35,0.280,0.000,0.618,0.061,0.227,0.106,0.063,0.220,0.373,0.078,0.594,1
35,T36,0.505,0.204,0.721,0.258,0.295,0.340,0.543,0.776,0.347,0.183,0.234,1
36,T37,0.084,0.648,0.338,0.152,0.038,0.255,0.480,0.196,0.707,0.150,0.625,1
37,T38,0.486,0.333,0.809,0.258,0.280,0.383,0.354,0.816,0.293,0.307,0.219,1
38,T39,0.458,0.407,0.338,0.061,0.326,0.128,0.071,0.627,0.387,0.150,0.125,1
39,T40,0.168,0.852,0.103,0.152,0.394,0.234,0.094,0.420,0.600,0.118,0.438,1
40,T41,0.346,0.370,0.662,0.061,0.098,0.043,0.055,0.327,0.560,0.183,0.625,1
41,T42,0.252,0.583,0.088,0.379,0.364,0.489,0.409,0.500,0.573,0.163,0.344,1
42,T43,0.318,0.481,0.412,0.061,0.538,0.340,1.000,0.571,0.000,1.000,0.219,1
43,T44,0.505,0.148,0.721,0.106,0.182,0.298,0.244,0.612,0.280,0.059,0.203,1